# This code-samples file is used by the MeiliSearch documentation
# Every example written here will be automatically fetched by
# the documentation on build
# You can read more on https://github.com/meilisearch/documentation/tree/master/.vuepress/code-samples
---
get_one_index_1: |-
list_all_indexes_1: |-
create_an_index_1: |-
update_an_index_1: |-
delete_an_index_1: |-
get_one_document_1: |-
get_documents_1: |-
add_or_replace_documents_1: |-
add_or_update_documents_1: |-
delete_all_documents_1: |-
delete_one_document_1: |-
delete_documents_1: |-
search_post_1: |-
get_update_1: |-
get_all_updates_1: |-
  var updates = await client.IndexAsync("movies").GetAllUpdateStatus();
  foreach (UpdateStatus update in updates)
  {
      Console.WriteLine(update.Status);
  }
get_keys_1: |-
get_settings_1: |-
update_settings_1: |-
reset_settings_1: |-
get_synonyms_1: |-
update_synonyms_1: |-
reset_synonyms_1: |-
get_stop_words_1: |-
update_stop_words_1: |-
reset_stop_words_1: |-
get_ranking_rules_1: |-
update_ranking_rules_1: |-
reset_ranking_rules_1: |-
get_distinct_attribute_1: |-
  string result = await client.IndexAsync("shoes").GetDistinctAttribute();
update_distinct_attribute_1: |-
  UpdateStatus result = await client.IndexAsync("shoes").UpdateDistinctAttribute("skuid");
reset_distinct_attribute_1: |-
  UpdateStatus result = await client.IndexAsync("shoes").ResetDistinctAttribute();
get_searchable_attributes_1: |-
update_searchable_attributes_1: |-
reset_searchable_attributes_1: |-
get_filterable_attributes_1: |-
  IEnumerable<string> attributes = await client.IndexAsync("movies").GetFilterableAttributes();
  foreach (string attribute in attributes)
  {
      Console.WriteLine(attribute);
  }
update_filterable_attributes_1: |-
  List<string> attributes = new() { "genres", "director" };
  UpdateStatus result = await client.Index("movies").UpdateFilterableAttributesAsync(attributes);
reset_filterable_attributes_1: |-
  UpdateStatus result = await client.Index("movies").ResetFilterableAttributesAsync();
get_displayed_attributes_1: |-
update_displayed_attributes_1: |-
reset_displayed_attributes_1: |-
get_index_stats_1: |-
get_indexes_stats_1: |-
get_health_1: |-
get_version_1: |-
distinct_attribute_guide_1: |-
field_properties_guide_searchable_1: |-
field_properties_guide_displayed_1: |-
filtering_guide_1: |-
  SearchQuery filters = new SearchQuery() { Filter = "release_date > \"795484800\"" };
  SearchResult<Movie> movies = await client.Index("movies").SearchAsync<Movie>("Avengers", filters);
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
filtering_guide_2: |-
  SearchQuery filters = new SearchQuery() { Filter = "release_date > 795484800 AND (director =
  \"Tim Burton\" OR director = \"Christopher Nolan\")" };
  SearchResult<Movie> movies = await client.Index("movies").SearchAsync<Movie>("Batman", filters);
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
filtering_guide_3: |-
  SearchQuery filters = new SearchQuery() { Filter = "director = \"Jordan Peele\"" };
  SearchResult<Movie> movies = await client.Index("movies").SearchAsync<Movie>("horror", filters);
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
filtering_guide_4: |-
  SearchQuery filters = new SearchQuery() { Filter = "rating >= 3 AND (NOT director = \"Tim Burton\"" };
  SearchResult<Movie> movies = await client.Index("movies").SearchAsync<Movie>("Planet of the Apes", filters);
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
search_parameter_guide_query_1: |-
search_parameter_guide_offset_1: |-
search_parameter_guide_limit_1: |-
search_parameter_guide_retrieve_1: |-
search_parameter_guide_crop_1: |-
search_parameter_guide_highlight_1: |-
search_parameter_guide_filter_1: |-
search_parameter_guide_filter_2: |-
search_parameter_guide_matches_1: |-
settings_guide_synonyms_1: |-
settings_guide_stop_words_1: |-
settings_guide_ranking_rules_1: |-
settings_guide_distinct_1: |-
settings_guide_searchable_1: |-
settings_guide_displayed_1: |-
documents_guide_add_movie_1: |-
search_guide_1: |-
search_guide_2: |-
getting_started_add_documents_md: |-
  ```bash
  dotnet add package MeiliSearch
  ```

  ```csharp
  using System.IO;
  using System.Text.Json;
  using Meilisearch;
  using System.Threading.Tasks;
  using System.Collections.Generic;

  namespace meilisearch_demo
  {
      public class Movie
      {
          public string Id { get; set; }
          public string Title { get; set; }
          public string Poster { get; set; }
          public string Overview { get; set; }
          public IEnumerable<string> Genres { get; set; }
      }

      internal class Program
      {
          static async Task Main(string[] args)
          {
              MeilisearchClient client = new MeilisearchClient("http://localhost:7700", "masterKey");
              var options = new JsonSerializerOptions
              {
                  PropertyNameCaseInsensitive = true
              };

              string jsonString = await File.ReadAllTextAsync("movies.json");
              var movies = JsonSerializer.Deserialize<IEnumerable<Movie>>(jsonString, options);

              var index = client.Index("movies");
              await index.AddDocumentsAsync<Movie>(movies);
          }
      }
  }
  ```
  [About this SDK](https://www.github.com/meilisearch/meilisearch-dotnet)
getting_started_search_md: |-
  ```csharp
  MeilisearchClient client = new MeilisearchClient("http://localhost:7700", "masterKey");
  var index = client.Index("movies");

  SearchResult<Movie> movies = await index.SearchAsync<Movie>("harry pottre");
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
  ```
  [About this SDK](https://www.github.com/meilisearch/meilisearch-dotnet)
faceted_search_update_settings_1: |-
faceted_search_filter_1: |-
  SearchQuery filters = new SearchQuery()
  {
      Filter = new string[][]
      {
          new string[] {"genres = Horror", "genres = Mystery"},
          new string[] {"director = \"Jordan Peele\""}
      }
  };

  SearchResult<Movie> movies = await client.Index("movies").SearchAsync<Movie>("thriller", filters);
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
faceted_search_facets_distribution_1: |-
  SearchQuery filters = new SearchQuery()
  {
      FacetsDistribution = new string[] { "genres" }
  };

  SearchResult<Movie> movies = await client.Index("movies").SearchAsync<Movie>("Batman", filters);
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
faceted_search_walkthrough_filterable_attributes_1: |-
faceted_search_walkthrough_filter_1: |-
faceted_search_walkthrough_facets_distribution_1: |-
add_movies_json_1: |-
post_dump_1: |-
get_dump_status_1: |-
phrase_search_1: |-
sorting_guide_update_sortable_attributes_1: |-
sorting_guide_update_ranking_rules_1: |-
sorting_guide_sort_parameter_1: |-
sorting_guide_sort_parameter_2: |-
get_sortable_attributes_1: |-
update_sortable_attributes_1: |-
reset_sortable_attributes_1: |-
search_parameter_guide_sort_1: |-
geosearch_guide_filter_settings_1: |-
  List<string> attributes = new() { "_geo" };
  UpdateStatus result = await client.Index("movies").UpdateFilterableAttributesAsync(attributes);
geosearch_guide_filter_usage_1: |-
  SearchQuery filters = new SearchQuery() { Filter = "_geoRadius(45.4628328, 9.1076931, 2000)" };
  SearchResult<Restaurant> restaurants = await client.Index("restaurants").SearchAsync<Restaurant>("", filters);
  foreach (var restaurant in restaurants.Hits)
  {
      Console.WriteLine(restaurant.Name);
  }
geosearch_guide_filter_usage_2: |-
  SearchQuery filters = new SearchQuery()
  {
      Filter = new string[] { "_geoRadius(45.4628328, 9.1076931, 2000) AND type = pizza" }
  };

  SearchResult<Restaurant> restaurants = await client.Index("restaurants").SearchAsync<Restaurant>("restaurants", filters);
  foreach (var restaurant in restaurants.Hits)
  {
      Console.WriteLine(restaurant.Name);
  }
geosearch_guide_sort_settings_1: |-
  List<string> attributes = new() { "_geo" };
  UpdateStatus result = await client.Index("restaurants").UpdateSortableAttributesAsync(attributes);
geosearch_guide_sort_usage_1: |-
  SearchQuery filters = new SearchQuery()
  {
      Sort = new string[] { "_geoPoint(48.8583701,2.2922926):asc" }
  };

  SearchResult<Restaurant> restaurants = await client.Index("restaurants").SearchAsync<Restaurant>("", filters);
  foreach (var restaurant in restaurants.Hits)
  {
      Console.WriteLine(restaurant.Name);
  }
geosearch_guide_sort_usage_2: |-
  SearchQuery filters = new SearchQuery()
  {
      Sort = new string[] {
            "_geoPoint(48.8583701,2.2922926):asc",
            "rating:desc"
      }
  };

  SearchResult<Restaurant> restaurants = await client.Index("restaurants").SearchAsync<Restaurant>("restaurants", filters);
  foreach (var restaurant in restaurants.Hits)
  {
      Console.WriteLine(restaurant.Name);
  }
