# This code-samples file is used by the MeiliSearch documentation
# Every example written here will be automatically fetched by
# the documentation on build
# You can read more on https://github.com/meilisearch/documentation/tree/master/.vuepress/code-samples
---
get_one_index_1: |-
list_all_indexes_1: |-
create_an_index_1: |-
update_an_index_1: |-
delete_an_index_1: |-
get_one_document_1: |-
get_documents_1: |-
add_or_replace_documents_1: |-
add_or_update_documents_1: |-
delete_all_documents_1: |-
delete_one_document_1: |-
delete_documents_1: |-
search_post_1: |-
get_update_1: |-
get_all_updates_1: |-
get_keys_1: |-
get_settings_1: |-
update_settings_1: |-
reset_settings_1: |-
get_synonyms_1: |-
update_synonyms_1: |-
reset_synonyms_1: |-
get_stop_words_1: |-
update_stop_words_1: |-
reset_stop_words_1: |-
get_ranking_rules_1: |-
update_ranking_rules_1: |-
reset_ranking_rules_1: |-
get_distinct_attribute_1: |-
update_distinct_attribute_1: |-
reset_distinct_attribute_1: |-
get_searchable_attributes_1: |-
update_searchable_attributes_1: |-
reset_searchable_attributes_1: |-
get_filterable_attributes_1: |-
update_filterable_attributes_1: |-
reset_filterable_attributes_1: |-
get_displayed_attributes_1: |-
update_displayed_attributes_1: |-
reset_displayed_attributes_1: |-
get_index_stats_1: |-
get_indexes_stats_1: |-
get_health_1: |-
get_version_1: |-
distinct_attribute_guide_1: |-
field_properties_guide_searchable_1: |-
field_properties_guide_displayed_1: |-
filtering_guide_1: |-
filtering_guide_2: |-
filtering_guide_3: |-
filtering_guide_4: |-
search_parameter_guide_query_1: |-
search_parameter_guide_offset_1: |-
search_parameter_guide_limit_1: |-
search_parameter_guide_retrieve_1: |-
search_parameter_guide_crop_1: |-
search_parameter_guide_highlight_1: |-
search_parameter_guide_filter_1: |-
search_parameter_guide_filter_2: |-
search_parameter_guide_matches_1: |-
settings_guide_synonyms_1: |-
settings_guide_stop_words_1: |-
settings_guide_ranking_rules_1: |-
settings_guide_distinct_1: |-
settings_guide_searchable_1: |-
settings_guide_displayed_1: |-
documents_guide_add_movie_1: |-
search_guide_1: |-
search_guide_2: |-
getting_started_add_documents_md: |-
  ```bash
  dotnet add package MeiliSearch
  ```

  ```csharp
  using System.IO;
  using System.Text.Json;
  using Meilisearch;
  using System.Threading.Tasks;
  using System.Collections.Generic;

  namespace meilisearch_demo
  {
      public class Movie
      {
          public string Id { get; set; }
          public string Title { get; set; }
          public string Poster { get; set; }
          public string Overview { get; set; }
          public IEnumerable<string> Genres { get; set; }
      }

      internal class Program
      {
          static async Task Main(string[] args)
          {
              MeilisearchClient client = new MeilisearchClient("http://localhost:7700", "masterKey");
              var options = new JsonSerializerOptions
              {
                  PropertyNameCaseInsensitive = true
              };

              string jsonString = await File.ReadAllTextAsync("movies.json");
              var movies = JsonSerializer.Deserialize<IEnumerable<Movie>>(jsonString, options);

              var index = await client.Index("Movies");
              await index.AddDocuments<Movie>(movies);
          }
      }
  }
  ```
  [About this SDK](https://www.github.com/meilisearch/meilisearch-dotnet)
getting_started_search_md: |-
  ```csharp
  MeilisearchClient client = new MeilisearchClient("http://localhost:7700", "masterKey");
  var index = await client.Index("Movies");

  SearchResult<Movie> movies = await index.Search<Movie>("harry pottre");
  foreach (var movie in movies.Hits)
  {
      Console.WriteLine(movie.Title);
  }
  ```
  [About this SDK](https://www.github.com/meilisearch/meilisearch-dotnet)
faceted_search_update_settings_1: |-
faceted_search_filter_1: |-
faceted_search_facets_distribution_1: |-
faceted_search_walkthrough_filterable_attributes_1: |-
faceted_search_walkthrough_filter_1: |-
faceted_search_walkthrough_facets_distribution_1: |-
add_movies_json_1: |-
post_dump_1: |-
get_dump_status_1: |-
phrase_search_1: |-
sorting_guide_update_sortable_attributes_1: |-
sorting_guide_update_ranking_rules_1: |-
sorting_guide_sort_parameter_1: |-
sorting_guide_sort_parameter_2: |-
get_sortable_attributes_1: |-
update_sortable_attributes_1: |-
reset_sortable_attributes_1: |-
search_parameter_guide_sort_1: |-
geosearch_guide_filter_settings_1: |-
geosearch_guide_filter_usage_1: |-
geosearch_guide_filter_usage_2: |-
geosearch_guide_sort_settings_1: |-
geosearch_guide_sort_usage_1: |-
geosearch_guide_sort_usage_2: |-
